version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    reviewers:
      - '@yeswanth'
    assignees:
      - '@yeswanth'
    commit-message:
      prefix: 'deps'
      include: 'scope'
    groups:
      production-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
          - 'typescript'
      development-dependencies:
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
          - 'typescript'
        update-types:
          - 'minor'
          - 'patch' 